idf_component_register(SRCS "heap_manager.c"
                            "heap_probe.c"
                            "lcd_nv3041a.c"
                            "http_load.c"
                            "mem_monitor.c"
                            "mem_snapshot.c"
                            "task_stats.c"
                            "wifi_conn.c"
                       INCLUDE_DIRS ".")
